### ISSUE TITLE
drvloader Load incomplete

### ISSUE THREAD

**Issue by stonedreamforest** [tandasat/DrvLoader#1]

**Comment by stonedreamforest** [comment]
![2017-06-05_21-22-50](https://cloud.githubusercontent.com/assets/16742566/26785621/e965a890-4a35-11e7-8845-b29a79adabb7.gif)

**Comment by tandasat** [comment]
Thank you for reporting the issue. Is the issue not being able to load KMDF drivers? 

This project is designed for NT drivers. I will take a look at what I can do, but probably I will just update documents to state supported driver types.

**Comment by stonedreamforest** [comment]
yes ,can't load kmdf drivers.

**Comment by tandasat** [comment]
Thank you, acknowledged.
